version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - dotnet build SampleWebAppForAWS/SampleWebAppForAWS.csproj
  post_build:
    commands:
      - dotnet publish -c Release -r linux-x64 SampleWebAppForAWS/SampleWebAppForAWS.csproj
artifacts:
  files:
    - '**/*'
  base-directory: SampleWebAppForAWS/bin/Release/netcoreapp3.1/linux-x64/publish/
  discard-paths: no
